version: "3"

services:
  krakend:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:watch
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "8080:8080"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]

  server_api:
    build: server_api/
    ports:
      - "5001:5001"
    depends_on:
      - krakend

  transaction_api:
    build: transaction_api/
    ports:
      - "5002:5002"
    depends_on:
      - krakend

networks:
    default:
      external:
        name: test
